"""changed short link field

Revision ID: 427a43264219
Revises: 
Create Date: 2026-07-29 20:54:08.897101

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '427a43264219'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.drop_index('ix_url_map_timestamp')

    op.drop_table('url_map')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('url_map',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('original', sa.VARCHAR(), nullable=False),
    sa.Column('short', sa.VARCHAR(), nullable=True),
    sa.Column('timestamp', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('url_map', schema=None) as batch_op:
        batch_op.create_index('ix_url_map_timestamp', ['timestamp'], unique=False)

    # ### end Alembic commands ###
